# Generated by Django 3.2.7 on 2021-12-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
